### ISSUE TITLE
Cannot create a VM with two flexible GPUs

### ISSUE THREAD

**Issue by apotier** [outscale/terraform-provider-outscale#220]
### Terraform Version

```
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.66.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/outscale-dev/outscale v0.5.0
```

### Terraform Configuration Files

```terraform
...
```

### Debug Output
attached:[terraform_bug_oustcale.log](https://github.com/outscale-dev/terraform-provider-outscale/files/9918254/terraform_bug_oustcale.log)

### Crash Output

N/A

### Expected Behavior
two GPU links should have been created and pushed to the state.

### Actual Behavior
Both links were created but only one was push

ed to the state. I also got a 409 error. It looks like the links VM<>GPU are created twice.

### Steps to Reproduce
Create any machine with two fgpus attached.

### Additional Context
N/A

### References
N/A

**Comment by outscale-toa** [comment]
Hi @apotier ,
Thanks for reaching us, we are looking at your issue.

Best regards,

**Comment by outscale-toa** [comment]
Hi @apotier 

We are working to find a workaround for terraform plugin.
For the moment, you can use ```depends_on``` in second  gpu_link like:
```
...

resource "outscale_flexible_gpu_link" "link_fGPU-1" {
    flexible_gpu_id              =  outscale_flexible_gpu.fGPU-1.flexible_gpu_id
    vm_id                        = outscale_vm.MaVM.vm_id
}

resource "outscale_flexible_gpu_link" "link_fGPU-2" {
    flexible_gpu_id              =  outscale_flexible_gpu.fGPU-2.flexible_gpu_id
    vm_id                        = outscale_vm.MaVM.vm_id
    depends_on= [outscale_flexible_gpu_link.link_fGPU-1]
} 
```
Best regards,

**Comment by outscale-toa** [comment]
Merge in #409
