### ISSUE TITLE
Need examples for the creation of NICs

### ISSUE THREAD

**Issue by ihaz** [outscale/terraform-provider-outscale#299]
Hello,

Users ask us for examples of how to create a nic with terraform.
Can you please add some examples

Regards

**Comment by FredericBerot-Armand** [comment]
Hi @ihaz

Thanks for reaching us, we will write an example for nics.

Best regards,

**Comment by RaitoBezarius** [comment]
This was closed as completed but the PR mentioned was never merged, is this completed?
