### ISSUE TITLE
outscale_tag and outscale_tags are not documented

### ISSUE THREAD

**Issue by albundy83** [outscale/terraform-provider-outscale#314]
Hello,

it seems that outscale_tag and outscale_tags are not documented (data source and resource).
Maybe it's an oversight ?

**Comment by outscale-toa** [comment]
Hello @albundy83,

It is not an oversight, outscale_tag (resource/datasources) have been deprecated and will be remove soon,
It is recommended to set tags inside the resources rather than using outscale_tag.

Best regards,
