### ISSUE TITLE
Add tags support for bsu

### ISSUE THREAD

**Issue by L00PBACK** [outscale/terraform-provider-outscale#337]
### Current Terraform Version

```
Terraform v1.4.2
```

### Use-cases

When using the resource `"outscale_vm"` we can't set tags on volume under the argument `"block_device_mappings"  { bsu }`

### Attempted Solutions

I've tried to use the resources `"outscale_volume"` and `"outscale_volumes_link"` to set up tags, it works fine.  
But in my case when i destroyed an instance it destroyed the volumes because of my module.

### Proposal

Is there a way to get around this and manage tags with `bsu` and not `"outscale_volume*"` resources ?

### References

Does this PR solve this ? : https://github.com/outscale/terraform-provider-outscale/pull/288

**Comment by outscale-toa** [comment]
Hello @L00PBACK,

Yes the fix is on this PR #338

Best regard,

**Comment by outscale-toa** [comment]
Fixed in #338
