### ISSUE TITLE
bug with provider 0.7.0

### ISSUE THREAD

**Issue by naicoram01** [outscale/terraform-provider-outscale#341]
Hi,

I'm using the provider 0.7.0 and today when I want to apply my plan with "terraform apply" I had this error output :
Stack trace from the terraform-provider-outscale_v0.7.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x11733b3]

goroutine 72 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.dataSourceOutscaleOApiVMSRead.func1()
        github.com/terraform-providers/terraform-provider-outscale/outscale/data_source_outscale_vms.go:88 +0x103
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/wait.go:22 +0x6c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:103 +0x1bb
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:80 +0x1db
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x11733b3]

goroutine 131 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.dataSourceOutscaleOApiVMSRead.func1()
        github.com/terraform-providers/terraform-provider-outscale/outscale/data_source_outscale_vms.go:88 +0x103
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/wait.go:22 +0x6c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:103 +0x1bb
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:80 +0x1db
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x11bc630]

goroutine 33 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.resourceOutscaleOAPINetRead.func1()
        github.com/terraform-providers/terraform-provider-outscale/outscale/resource_outscale_net.go:106 +0x100
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/wait.go:22 +0x6c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:103 +0x1bb
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:80 +0x1db
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x11733b3]

goroutine 47 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.dataSourceOutscaleOApiVMSRead.func1()
        github.com/terraform-providers/terraform-provider-outscale/outscale/data_source_outscale_vms.go:88 +0x103
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/wait.go:22 +0x6c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:103 +0x1bb
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:80 +0x1db
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x11733b3]

goroutine 119 [running]:
github.com/terraform-providers/terraform-provider-outscale/outscale.dataSourceOutscaleOApiVMSRead.func1()
        github.com/terraform-providers/terraform-provider-outscale/outscale/data_source_outscale_vms.go:88 +0x103
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Retry.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/wait.go:22 +0x6c
github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState.func1()
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:103 +0x1bb
created by github.com/hashicorp/terraform-plugin-sdk/helper/resource.(*StateChangeConf).WaitForState
        github.com/hashicorp/terraform-plugin-sdk@v1.17.1/helper/resource/state.go:80 +0x1db

Error: The terraform-provider-outscale_v0.7.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
========================

Can you help please ?

**Comment by outscale-toa** [comment]
Hi @naicoram01,
Thanks for reaching us,
Can you please add the configuration file please?
Thanks,
