### ISSUE TITLE
Ability to Set a Routing Table as Main through code

### ISSUE THREAD

**Issue by cvedia-mdsol** [outscale/terraform-provider-outscale#362]
### Current Terraform Version

```
Terraform v1.4.6
on windows_amd64
```

### Use-cases

Currently, we are able to create Routing Tables via Terraform but have to mark the table as a "main" one via the Cockpit console so we are required to take that extra step to finalize the configuration.

### Attempted Solutions

From research, we should be able to update this configuration through use of [main_route_table_association]. Below is the code we ran and the response.

response
```
Error: Invalid resource type

  on ..\..\modules\network\routing_table.tf line 97, in resource "outscale_main_route_table_association" "main-route_table":
  97: resource "outscale_main_route_table_association" "main-route_table"{

The provider outscale/outscale does not support resource type "outscale_main_route_table_association".
```
code
```
resource "outscale_main_route_table_association" "main-route_table"{
     vpc_id = "outscale_net.vpc-setup.net_id"
     route_table_id = "outscale_route_table.rt-private.route_table_id"  
}
```

### Proposal

If the command is supported we should be able to finalize our route table configuration with just Terraform similar to how [aws_main_route_table_association] functions. The required values are 'VPC ID' and 'Route Table ID'.

### References

Below is a reference to the Terraform Registry AWS command which support the type of update we are looking for:
https://registry.terraform.io/providers/hashicorp/aws/3.1.0/docs/resources/main_route_table_association

This is the current list of available data sources for Outscale:
https://registry.terraform.io/providers/outscale/outscale/latest/docs

**Comment by cvedia-mdsol** [comment]
Hi @outscale-toa . Has there been any update in regards to this particular request? If not, can you please provide an ETA so we know when to expect the feature to be available?

Thank you.

**Comment by cvedia-mdsol** [comment]
Hi @outscale-toa . Just wanted to follow up again since we are working on additional updates to the VPC via Terraform and we are highly interesting in this feature.

**Comment by outscale-toa** [comment]
Hi @cvedia-mdsol,
Once the API issue has been addressed we will implement in terraform as soon as it will be available in our API.

**Comment by outscale-toa** [comment]
Hi @cvedia-mdsol,

We have an API issue with set ``` main route_table ``` call.
Once the API issue has been addressed we will implement in terraform as soon as it will be available in our API. 

Thanks,

**Comment by jacen05** [comment]
Hello @outscale-toa, is there any news on this issue?

**Comment by outscale-toa** [comment]
Hi @jacen05,
  Sorry for the delay.
  It is on developement  by ours api team.

Best regards,

**Comment by cvedia-mdsol** [comment]
@outscale-toa thanks for the update. please keep us posted on anything additional.
