### ISSUE TITLE
Implement snapshot creation before volume deletion by terraform destroy, as in aws provider

### ISSUE THREAD

**Issue by gamcorn** [outscale/terraform-provider-outscale#367]
Terraform version = 1.2.4
Outscale provider version = 0.8.2

### Use-cases
It could be very useful to be able to create a snapshot from a volume automatically before the Terraform destroy command tears down the resource. This would allow managing data on volume as persistent without having to keep an unattached volume active. This feature is available on other providers such as AWS.

### Proposal
Refer to the AWS issue on the same subject here: [AWS_issue](https://github.com/hashicorp/terraform-provider-aws/issues/2109)

**Comment by outscale-toa** [comment]
Hi @gamcorn,

Thanks for reaching us, we are looking at your issue

Best regards,
