### ISSUE TITLE
Terraform want to rebuild VM if I add a secondary NIC

### ISSUE THREAD

**Issue by sylvain987** [outscale/terraform-provider-outscale#376]
### Terraform Version
```
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/outscale v0.9.0
+ provider registry.terraform.io/hashicorp/vault v3.15.0
```

### Terraform Configuration Files
```
resource "outscale_nic" "NIC-VM" {
    subnet_id          = "${data.outscale_subnet.subnet.subnet_id}"
    security_group_ids = [ for sg_id in "${data.outscale_security_groups.security_groups.security_groups}" : sg_id.security_group_id ]
}

resource "outscale_nic" "NIC-2-VM" {
    subnet_id = "subnet-a032f7cb"
    security_group_ids = ["sg-b412e6c0"]
}

resource "outscale_nic_link" "NIC-2-LINK-VM" {
    vm_id         = outscale_vm.VM-AFD.id
    device_number = "1"
    nic_id        = outscale_nic.NIC-2-VM.nic_id
}

resource "outscale_vm" "VM-AFD" {

    vm_initiated_shutdown_behavior = "${var.shutdown_behavior}"
    image_id                       = "${data.outscale_image.image.image_id}"
    performance                    = "${var.perf}"
    vm_type                        = "${var.vm_type}"
    nics {
        nic_id                     = outscale_nic.NIC-VM.nic_id
        device_number              = "0"
    }
    keypair_name                   = "${var.keypair_name}"
    block_device_mappings {
        device_name                = "/dev/sda1"
        bsu {
            volume_size            = "${var.size_disk_system}"
            volume_type            = "gp2"
            delete_on_vm_deletion  = true
        }
    }
}
...
```

### Debug Output
I create a gist here : https://gist.github.com/sylvain987/b8766b013a4d791e6c9c12224a354257

### Expected Behavior
When I rebuild the plan after add a NIC, Terraform do nothing.

### Actual Behavior
When I rebuild the plan after add a NIC, Terraform want to recreate the VM and the NIC.

### Steps to Reproduce
```
terraform plan -out=main.tfplan
terraform apply "main.tfplan"
terraform plan -out=main.tfplan
```

### Additional Context
I develop a module to create a VM with one NIC and several disks if it necessary. It works well and we use it to deployment our Red Hat servers on Outscale cloud. I receive a new useccase to a module that provides multiple NIC on a VM. As a test, I add 2 resources on the new module (it's a fork of the previous version). The module can create the VM with 2 NICs (the primary that already exist on the previous version and a secondary with a link). But when I recreate the plan, Terraform want to destroy the VM and the NICs.

**Comment by outscale-toa** [comment]
Hi @sylvain987 

Thanks for reaching us, we are looking at your issue

Best regards,

**Comment by outscale-toa** [comment]
Hello @sylvain987 

It is not recommended to mix NIC inside VM and link NIC ``` outscale_nic_link ```  resource (Your VM will be destroy in the next apply  because ``` nics block ``` in VM cannot be modify without destroy VM)

The best way is to use  "outscale_nic_link"  to link nics  to your VM 
REF:    [Terraform doc ](https://registry.terraform.io/providers/outscale/outscale/latest/docs/resources/nic_link)

Best Regards.

**Comment by sylvain987** [comment]
In addition of that, is it possible to add another interface in a configuration like in your example called "Create a VM with a NIC" in this link https://registry.terraform.io/providers/outscale-dev/outscale/latest/docs/resources/vm.
