### ISSUE TITLE
Unable to Reference Security Groups By Name For Rules

### ISSUE THREAD

**Issue by cvedia-mdsol** [outscale/terraform-provider-outscale#398]
Hi Team,

Having issues when creating Security Group Ingress Rules when referencing other Security Groups in Terraform. With the same code, it looks like I can use "security_group_id" but not "security_group_name".

For testing, I created a Security Group on the account manually on VPC then copied the same Name into code as reference. Same approach was done to plug in the ID.

### Terraform Version
```
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/outscale/outscale v0.9.1
```

### Terraform Configuration Files
Using Security Group ID (works)
```terraform
resource "outscale_security_group" "security_group" {
    description         = "testing security group"
    security_group_name = "my_test_sg"
    net_id              = "vpc-dbc90d16"
}

resource "outscale_security_group_rule" "rule_group" {
    security_group_id = outscale_security_group.security_group.security_group_id
    flow              = "Inbound"
    rules {
        from_port_range   = 636
        to_port_range     = 636
        ip_protocol       = "tcp"
        security_groups_members {
            account_id          = "123456"
            security_group_id = "sg-abc123"
        }
    }

}
```

Using Security Group Name (does not work)
```terraform
resource "outscale_security_group" "security_group" {
    description         = "testing security group"
    security_group_name = "my_test_sg"
    net_id              = "vpc-dbc90d16"
}

resource "outscale_security_group_rule" "rule_group" {
    security_group_id = outscale_security_group.security_group.security_group_id
    flow              = "Inbound"
    rules {
        from_port_range   = 636
        to_port_range     = 636
        ip_protocol       = "tcp"
        security_groups_members {
            account_id          = "123456"
            security_group_name = "ad-servers"
        }
    }

}
```

### Expected Behavior
Plan mentions the creation of the rule within 'Security Group A' linked to the other mentioned 'Security Group B'. After the changes, the rule should be created in 'Security Group A' and the terminal response would follow with 'Apply Complete'.

### Actual Behavior
Instead the Plan attempt to create the Rule but is unable to. The message below comes back in the terminal.
```
Error authorizing security group rule type: 400 Bad Request {
    "Errors": [
        {
            "Code": "5060",
            "Details": "",
            "Type": "InvalidResource"
        }
    ],
    "ResponseContext": {
            "RequestId": "4ea62bf9-6c38-470b-8795-9db3ead203e8"
        }
    }
```

### Steps to Reproduce
1.  Update code to create Security Group using "outscale_security_group"
2. Create rule for the same Security Group using "outscale_security_group_rule"
3. Use "security_group_name" and pick a name of an existing security group on the account
4. Run "terraform init" to load provider and dependencies
5. Run "terraform apply" and confirm

### Additional Context
The  security group referenced is tied to the VPC. The intention of this is to create and update the base Security Groups on the account in bulk with standardized rules.

Config Info
```terraform
# Terraform Config
terraform {
    required_version = ">= 0.13"
    required_providers {
        outscale = {
            source = "outscale/outscale"
        }
    }
}

# Outscale Provider
provider "outscale" {
    access_key_id = var.access_key_id
    secret_key_id = var.secret_key_id
    region = var.outscale_region
}
```

### References
Attempting to follow the code as referenced in the "Set an inbound rule from another security group" section on (https://registry.terraform.io/providers/outscale/outscale/latest/docs/resources/security_group_rule). Re-included below from the site.

```terraform
resource "outscale_security_group_rule" "security_group_rule02" {
    flow              = "Inbound"
    security_group_id = outscale_security_group.security_group01.security_group_id
    rules {
        from_port_range = "22"
        to_port_range   = "22"
        ip_protocol     = "tcp"
        security_groups_members {
            account_id          = "012345678910"
            security_group_name = "terraform-security-group-test-02"
        }
    }
}
```

**Comment by outscale-toa** [comment]
Hello @cvedia-mdsol,
```security_group_name ``` parameter can be use only in security group rule on public cloud (without net_id(VPC))
[security_group_name](https://registry.terraform.io/providers/outscale/outscale/latest/docs/resources/security_group_rule#security_group_name) - (Public Cloud only) The name of a source or destination security group that you want to link to the security group of the rule. 

```terraform
resource "outscale_security_group" "security_group" {
    description         = "testing security group"
    security_group_name = "my_test_sg"
    #net_id              = "vpc-dbc90d16" 
}

resource "outscale_security_group_rule" "rule_group" {
    security_group_id = outscale_security_group.security_group.security_group_id
    flow              = "Inbound"
    rules {
        from_port_range   = 636
        to_port_range     = 636
        ip_protocol       = "tcp"
        security_groups_members {
            account_id          = "123456"
            security_group_name = "ad-servers"
        }
    }

}
```
Best Regards,

**Comment by cvedia-mdsol** [comment]
Hi @outscale-toa. Thank you for clarifying this. We are creating everything behind the VPC instead of exposing on the Public Cloud.

Can we put this in a feature request for our team so we can make use of it in the future?

Thank you,

**Comment by outscale-toa** [comment]
Hi @cvedia-mdsol,
Yes you can put this in a feature request.
Thanks,

**Comment by cvedia-mdsol** [comment]
Thank you opening feature request via - https://github.com/outscale/terraform-provider-outscale/issues/399
