### ISSUE TITLE
IAM and EIM support

### ISSUE THREAD

**Issue by albundy83** [outscale/terraform-provider-outscale#413]
### Current Terraform Version

```
Terraform v1.6.6
```

### Use-cases
Add IAM and EIM management capability

Thanks for your help

**Comment by albundy83** [comment]
Great news, it seems that api has just been updated to support Policy and User creation :)

**Comment by albundy83** [comment]
Hello,

any update to add the IAM support ?
Thanks a lot

**Comment by outscale-mgo** [comment]
Hello, 
We are not going to implement IAM API as this require to be compatible with another API, which is a source of bug/incompatibility with Outscale API options.
But now that Outscale API support most of IAM/EIM we are going to implement it in terraform, but as this require the creations of new datasource/resources files this might still take some time.
Sorry for the delay.

**Comment by albundy83** [comment]
Thanks, that will be perfect :)

**Comment by albundy83** [comment]
Hello,

any update ?
