### ISSUE TITLE
block_device_mappings tag not working anywhere

### ISSUE THREAD

**Issue by silex27** [outscale/terraform-provider-outscale#443]
Hello

I keep getting not expected key everywhere within block_device_mappings
Based on the documentation, tag is available , but i had no luck with it. 

https://registry.terraform.io/providers/outscale/outscale/latest/docs/resources/image
I use this code to provision my instance and volume and I just want to add tag to created volumes. 
I tried to put tags inside content / bsu / after bsu block. No luck. 

```terraform
resource "outscale_vm" "instance" {
  for_each = local.vm_map

  image_id     = each.value.image_id
  vm_type      = each.value.vm_type
  keypair_name = "key-admin"
  nics {
    nic_id        = outscale_nic.nic_outscale[each.key].nic_id
    device_number = "0"
  }


dynamic "block_device_mappings" {
  for_each = each.value.volumes
  content {
    device_name = block_device_mappings.value.device_name
    bsu {
      volume_size        = block_device_mappings.value.size
      volume_type        = try(block_device_mappings.value.disk_type, var.default_disk_type)
      delete_on_vm_deletion = true
      iops                = try(block_device_mappings.value.iops, 13000)
    }
  }
}
```

**Comment by outscale-mgo** [comment]
Hello,
Thanks for reporting the issue.

If you are trying to add tags like this:

```terraform
dynamic "block_device_mappings" {
  for_each = each.value.volumes
  content {
    device_name = block_device_mappings.value.device_name
    tags {
      key   = "Name"
      value = "ah"
    }
    bsu {
      volume_size        = block_device_mappings.value.size
      volume_type        = try(block_device_mappings.value.disk_type, var.default_disk_type)
      delete_on_vm_deletion = true
      iops                = try(block_device_mappings.value.iops, 13000)
    }
  }
}
```
Then you are not trying to add a tag to a volume, but to the `block_device_mappings` elements of the Vms.
Documented here: https://registry.terraform.io/providers/outscale/outscale/latest/docs/resources/vm#block_device_mappings.

Otherwise, this issue seems hard to reproduce not knowing what is inside `local.vm_map`, and not knowing how you try to add tags. 

Also according to documentation, tags are available inside `Images` and `Vms`, but not inside `block_device_mappings`

**Comment by outscale-mgo** [comment]
If you try that:
```terraform
  dynamic "block_device_mappings" {
    for_each = each.value.volumes
    content {
      device_name = "div name"
      bsu {
        volume_size        = 10
        volume_type        = try(block_device_mappings.value.disk_type, "io1")
        delete_on_vm_deletion = true
        iops                = try(block_device_mappings.value.iops, 13000)
        tags {
          key   = "Name"
          value = "ja"
        }

      }
    }
  }
```
So with tags inside `bsu`
does it work ?
If not, what errors do you get ?
Thanks.

**Comment by silex27** [comment]
`│ Error: Unsupported block type
│ 
│   on .terraform/modules/outscale_module/main.tf line 61, in resource "outscale_vm" "instance":
│   61:       tags {
│ 
│ Blocks of type "tags" are not expected here.`

for this : 
`  dynamic "block_device_mappings" {
    for_each = each.value.volumes
    content {
      device_name = "div name"
      bsu {
        volume_size        = block_device_mappings.value.size
        volume_type        = try(block_device_mappings.value.disk_type, var.default_disk_type)
        delete_on_vm_deletion = true
        iops                = try(block_device_mappings.value.iops, 13000)
        tags {
          key   = "Name"
          value = "ja"
        }

      }
    }
  }`
  
  But its the same error always, like there : 
`  dynamic "block_device_mappings" {
  tags {
    key   = "Name"
    value = "ja"
  }
  for_each = each.value.volumes
  content {  `

or like this : 
`  content {    
    device_name = block_device_mappings.value.device_name
    tags {
      key   = "Name"
      value = "ja"
         }
    bsu {
      volume_size        = block_device_mappings.value.size
      volume_type        = try(block_device_mappings.value.disk_type, var.default_disk_type)
      delete_on_vm_deletion = true
      iops                = try(block_device_mappings.value.iops, 13000)

    }`

**Comment by silex27** [comment]
Understood, thank you, then local-exec is my only way, I was hoping that im just using tags at the wrong place.
