### ISSUE TITLE
Fail to import `ouscale_nic` if the NIC is attached to a public IP

### ISSUE THREAD

**Issue by john-scalingo** [outscale/terraform-provider-outscale#461]
### Terraform Version
```
Terraform v1.9.3
```

### Terraform Configuration Files
```terraform
resource "outscale_nic" "dashboard" {
  subnet_id   = outscale_subnet.log_host_subnet.id
  description = "..."

  security_group_ids = [outscale_security_group.sg_dashboard_instances.id]

  tags {
    key   = "Name"
    value = "My NIC"
  }
}

resource "outscale_public_ip" "dashboard_public_endpoint" {
  tags {
    key   = "Name"
    value = "My Public IP"
  }
}

resource "outscale_public_ip_link" "dashboard_public_endpoint_link" {
  nic_id       = outscale_nic.dashboard.id
  public_ip_id = outscale_public_ip.dashboard_public_endpoint.id
}

```

### Expected Behavior

With an existing configuration, i expect the import to work:

```
terraform import "outscale_nic.dashboard" "eni-XXXXXX"
```

### Actual Behavior

The import command crash with:

```
╷
│ Error: private_ips.0.link_public_ip: '': source data must be an array or slice, got map
│ 
│ 
╵

```

### Steps to Reproduce
1. Create a NIC linked to a Public IP
2. Import it on your terraform project using the terraform import command given earlier.

### Additional Context
To me it looks like the issue comes from this line: https://github.com/outscale/terraform-provider-outscale/blob/master/outscale/resource_outscale_nic.go#L63 and this line https://github.com/outscale/terraform-provider-outscale/blob/master/outscale/resource_outscale_nic.go#L168
Both of this type have been converted to `TypeSet` and `TypeList` when converting the code to terraform SDK v2 (https://github.com/outscale/terraform-provider-outscale/commit/ca94592be2dd3fbeac36a8841228ee7176b183e4).

To me this looks incorect because in your API doc it states that those two are indeed a Map and not any `Set` nor `List`: https://docs.outscale.com/api.html#tocs_readnicsresponse

```

{
  "Nics": [
    {
      [...]
      "LinkPublicIp": {
        "LinkPublicIpId": "string",
        "PublicDnsName": "string",
        "PublicIp": "string",
        "PublicIpAccountId": "string",
        "PublicIpId": "string"
      },
      "PrivateIps": [
        {
          [...]
          "LinkPublicIp": {
            "LinkPublicIpId": "string",
            "PublicDnsName": "string",
            "PublicIp": "string",
            "PublicIpAccountId": "string",
            "PublicIpId": "string"
          },
          [...]
        }
      ],
     [...]
    }
  ],
  [...]
}
```

**Comment by outscale-toa** [comment]
Hello @john-scalingo,

Thanks for reaching us, w'll fix it in the next release.

Best Regards
