### ISSUE TITLE
Fix links to Outscale documentation

### ISSUE THREAD

**Issue by jerome-jutteau** [outscale/terraform-provider-outscale#66]
Outscale documentation has moved to docs.outscale.com and a lot of links are still pointing to wiki.outscale.net.
This need to be fixed.

This mainly consist of updating vendor version for osc-sdk-go and fix website.

**Comment by outscale-toa** [comment]
Hello @jerome-jutteau,
Thanks for reaching us, we are looking at your issue

Best regards,
